TWEETS_PATH = Data/Tweets/
ITA_PATH = Data/Tweets/tweets_italia.csv
ENG_PATH = Data/Tweets/tweets_england.csv
FRA_PATH = Data/Tweets/tweets_france.csv
BRA_PATH = Data/Tweets/tweets_brasil.csv
IND_PATH = Data/Tweets/tweets_india.csv
MODEL_TRAIN_PATH=Data/Emotion_Model/Emotion_Text.csv
MODEL_VEC_PATH=Data/Emotion_Model/vectorizer.pickle
MODEL_PATH=Data/Emotion_Model/model_LR.sav
WORDCLOUD_PATH=Results/wordClouds/
TOPICS_PER_PERIOD_PATH=Results/Topics_per_period/
EMOTION_PATH=Results/Emotions/
EMOTION_PER_TOPIC_PATH = Results/Emotions_per_topic/
EPIDEMIC_PATH=Data/Epidemic_curve/
